using CookComputing.XmlRpc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SubDownloader.OpenSubtitlesAPI
{
    public struct ServerInfo
    {
        public string xmlrpc_version;
        public string xmlrpc_url;
        public string application;
        public string contact;
        public string website_url;
        public int users_online_total;
        public int users_online_program;
        public int users_loggedin;
        public string users_max_alltime;
        public string users_registered;
        public string subs_downloads;
        public string subs_subtitle_files;
        public string movies_total;
        public string movies_aka;
        public string total_subtitles_languages;
        public LastUpdateString last_update_strings;
        public DownloadLimits download_limits;
        public double seconds;
    }
    public struct DownloadLimits
    {
        public int global_24h_download_limit;
        public string client_ip;
        public string limit_check_by;
        public int client_24h_download_count;
        public int client_download_quota;
        public int client_24h_download_limit;
    }

    public struct LastUpdateString
    {
        public string aa;
        public string ab;
        public string af;
        public string ak;
        public string am;
        public string ar;
        public string an;
        public string as2;
        public string av;
        public string ae;
        public string ay;
        public string az;
        public string ba;
        public string bm;
        public string be;
        public string bn;
        public string bh;
        public string bi;
        public string bs;
        public string br;
        public string bg;
        public string ca;
        public string ch;
        public string ce;
        public string cu;
        public string cv;
        public string kw;
        public string co;
        public string cr;
        public string da;
        public string dv;
        public string dz;
        public string en;
        public string eo;
        public string et;
        public string ee;
        public string fo;
        public string fj;
        public string fi;
        public string fy;
        public string ff;
        public string gd;
        public string ga;
        public string gl;
        public string gv;
        public string gn;
        public string gu;
        public string ht;
        public string ha;
        public string he;
        public string hz;
        public string hi;
        public string ho;
        public string hr;
        public string hu;
        public string ig;
        public string io;
        public string ii;
        public string iu;
        public string ie;
        public string ia;
        public string id;
        public string ik;
        public string it;
        public string jv;
        public string ja;
        public string kl;
        public string kn;
        public string ks;
        public string kr;
        public string kk;
        public string km;
        public string ki;
        public string rw;
        public string ky;
        public string kv;
        public string kg;
        public string ko;
        public string kj;
        public string ku;
        public string lo;
        public string la;
        public string lv;
        public string li;
        public string ln;
        public string lt;
        public string lb;
        public string lu;
        public string lg;
        public string mh;
        public string ml;
        public string mr;
        public string mg;
        public string mt;
        public string mn;
        public string na;
        public string nv;
        public string nr;
        public string nd;
        public string ng;
        public string ne;
        public string nn;
        public string nb;
        public string no;
        public string ny;
        public string oc;
        public string oj;
        public string or;
        public string om;
        public string os;
        public string pa;
        public string pi;
        public string pl;
        public string pt;
        public string ps;
        public string qu;
        public string rm;
        public string rn;
        public string ru;
        public string sg;
        public string sa;
        public string si;
        public string sl;
        public string se;
        public string sm;
        public string sn;
        public string sd;
        public string so;
        public string st;
        public string es;
        public string sc;
        public string sr;
        public string ss;
        public string su;
        public string sw;
        public string sv;
        public string ty;
        public string ta;
        public string tt;
        public string te;
        public string tg;
        public string tl;
        public string th;
        public string ti;
        public string to;
        public string tn;
        public string ts;
        public string tk;
        public string tr;
        public string tw;
        public string ug;
        public string uk;
        public string ur;
        public string uz;
        public string ve;
        public string vi;
        public string vo;
        public string wa;
        public string wo;
        public string xh;
        public string yi;
        public string yo;
        //public string za;
        //public string zu;
    }
    [XmlRpcUrl("http://api.opensubtitles.org/xml-rpc")]
    public interface IOpenSubtitles : IXmlRpcProxy
    {
        [XmlRpcMethod("ServerInfo")]
        ServerInfo ServerInfo();
    }
}
